name: Validar Mensagens de Commit

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  validate-commits:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código
      uses: actions/checkout@v3

    - name: Obter mensagens dos commits
      run: |
        commits=$(git log origin/${{ github.base_ref }}..HEAD --pretty=format:"%s")
        echo "$commits" > commit_messages.txt

    - name: Validar mensagens dos commits
      run: |
        mensagens_invalidas=0
        while IFS= read -r commit; do
          if [[ ! $commit =~ ^(feat|fix|docs|chore|style|refactor|test|perf|deploy)(\([^)]+\))?!?:\  ]]; then
            echo "Mensagem de commit inválida: $commit"
            mensagens_invalidas=$((mensagens_invalidas + 1))
          fi
        done < commit_messages.txt

        if [ $mensagens_invalidas -ne 0 ]; then
          echo "❌ Algumas mensagens de commit não seguem o padrão Conventional Commits."
          exit 1
        fi

    - name: Mensagem de sucesso
      if: success()
      run: echo "✅ Todas as mensagens de commit seguem o padrão Conventional Commits."